language: ruby
rvm:
- 2.2
- 2.1
- 2.0
- 1.9.3
sudo: required
services:
- docker
script:
- >
  wget -qO- bit.ly/ansibletest | env
  DOCKER_IMAGES="ubuntu:14.04 ubuntu:16.04"
  ANSIBLE_VERSIONS="1.4.4 1.5.4 1.6.1 1.7.2 1.8.4 1.9.2 2.0.0.2 2.1.0.0" sh
after_failure:
- cat role-tester-ansible-master/.kitchen/logs/*.log | grep -v '^I, '
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  slack:
    secure: XkDRP3k+U8s1LNjKQhhG/lEN54k8gzrXIwe/oyC83FXH5y/5mYOV87K1I/MoSRtFSy943SPsDmUpr9tyw6KUO2z3NR+iVJEyyOwoth9G3wuVygzxOLwkPe9R+FQlir7xSlFbf08Z5JJc0R61wS+h8wjjMMyNTXlllnGUGCQOxh2PfMGY6D2kpYVM7J03UBZoQMFq+v+g7xVDv9+H/dHhyYwhqjKau7vpGgurz4D0qBxgO1WUywQ69J2vPEsDWVNguwZP1i1+g19tRv2mK1V8ignJDqFggb8AI845tdvSyhkxyZAjvbAr/jm41+VlEB2fddl+UsxrVuiaOvht8QtcYsbQ0yf7W+4+OY4PNwarqlXd1fWPOJfacn+0IZ+T6tn6MA/xY+6k4xa/9vDNrAPbvTRtNr9rwAf9iObeOn3TV970l6Tbr4VyI4OFFMNeMef/vCMDDiILRs8nvBQU+bm7LWS/SsIDUSoirYLFJam2HAXRG6LkPamQkxN8x0KdmDjUEmJvM93jQ9UMrlr48a32gqkcoGHDWoNfRLTYFUa6YcOnEC/ruv5bPGZzwwj9owOVUoEBbMGM0mhqBQSjoWDh7RB8qDjnwp3Tt4lHwgyIn4mPUXIwAwcb/FCXOo/edDmCC9iz1sQZUnENdu34DMAuvQ0knasCGFjdp6IPNS38ixM=
  email:
    recipients:
      secure: l8k0HKngy3Gcq5KrXnejzvzDLjBi34X0QBE2dZy9eGScqgvhfDRv3nb3iPOXioyUXsRGfiKehHpmU+D1IgnB/JRq5qqjIJlVdfYxI/bwj1QKDLhxkkX7NTxEzEDn0VLUFq6smeChMgwLU453E+dRrTb9iYF9HA7mxouzp66wwlX+mR+x2SxWiN7JdBENtwAOErxNW8kDwHcbeT7qoAxwLely50b7A7A2KZ3u7hMDAjxl4DHeGTfySr/udDDGedFlJMSZ25zCpdsZPSTwj9Q73u6eb1Ajq/bVu81Hhb8kLNP77fzTTmkfZU4ZmpVup/tt2slSef//ptP7TzaficaSqUqPjmni+gbkXwk2vnCHZ7I/AunebryrjmHzuSjrjugazeRB0jLmD0GVh3swV7b8tDROdW2zXXGRYRonkj2ajSOxEI09It5fj/38bls3No569+f22gIEQl3Vl3lG6eABWlscdFMVCElhWzFJ6aEAaqDfjkwTAWxfXJHS2VVi8JIy3gTlK30IyL87Y158REXromKUEo3H2Aa/YzbEhZHIJeGGirCw30QlALM6pqvHI6EndEtR9pCzN76hnHW1TkjNlh99vfWZPDpuGfMSQ5H8Fr/GZRRW/MIqIzrVCBfMQp/Z5pa0YbLCXFHqLW9WI11V5FAOqqwzvB2xeZIf38U32eU=
