---
# Update APT configuration
- name: add universe repository
  apt_repository: >
    repo="deb http://archive.ubuntu.com/ubuntu trusty universe"
    state=present
  register: universe_result
  sudo: yes

# Download keys and package lists
- name: apt-get update
  apt: update_cache=yes cache_valid_time=0
  sudo: yes
  when: universe_result.changed
